### ISSUE TITLE
Uncaught Error if project doesn't exist

### ISSUE THREAD

**Issue by karster** [spirit-dev/php-sonarqube-api#2]
Fatal error: Uncaught Error: Wrong parameters for SonarQube\Exception\RuntimeException([string $message [, long $code [, Throwable $previous = NULL]]]) in C:\xampp\htdocs\scrum\project-rating\vendor\spirit-dev\php-sonarqube-api\lib\SonarQube\HttpClient\Listener\ErrorListener.php on line 75

SonarQube returns message with array key `errors` instead of `error`

**Comment by karster** [comment]
Please review my pull request #3

**Comment by spirit-dev** [comment]
Thank you @karster for this pull request :)
